language: python
python:
  - python: 2.7
    env: TOXENV=py2.7-django1.8
  - python: 2.7
    env: TOXENV=py2.7-django1.11
  - python: 3.5
    env: TOXENV=py3-django1.11
  - python: 3.5
    env: TOXENV=py3-django2.0
install:
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - tox

